---
title: "MWAS analysis - Visualization"
author: "Zhenjiang Li"
date: today
toc: true
toc_expand: 2
format: 
  html:
    code-fold: true
    html-math-method: katex
    fontsize: 16pt
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 1.5rem
embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: console
---

## Environment Setup {.hidden}

```{=html}
<style type="text/css">
caption, .table-caption {
  text-align: left;
}
</style>
```

```{r}
#| echo: false

options(scipen=999)

source(fs::path(here::here(),"2_longitudinal_metabolomics","!libraries.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!directories.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!functions.R"))

library(kableExtra)
library(ggplot2)
library(nlme)
library(ggh4x)

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
#| label: shorten-long-path
#| include: false

create_shortcut <- function(path, short_cut, drive)
{
  return(
    sub(gsub("\\)", "\\\\)", gsub("\\(", "\\\\(", short_cut)), paste0(drive, ":"), path))
}

if(nchar(dir_data) > 80)
{
  system("subst x: /D")
  short_cut <- dir_home |> dirname()
  system(paste0("subst x: \"", short_cut, "\""))
  
  dir_objects_names <- ls(pattern = "^dir_")
  
  dir_list <- mget(dir_objects_names)
  
  dir_list_shortened <- lapply(
    dir_list,
    function(y) create_shortcut(y, short_cut, "x")
  )
  list2env(dir_list_shortened, envir = .GlobalEnv)  
}

rm(dir_objects_names, short_cut, dir_list, dir_list_shortened)
```

## Model Parameters

```{r}
chemical_names <- c("PFOS", "PFHxS", "PFHpS", "PFOA", "PFNA", "PFDA", "PFHpA", "PFUnDa")

chemical_variables <- c(
  "pfos_untargeted_plasma",
  "pf_hx_s_untargeted_plasma",
  "pf_hp_s_untargeted_plasma",
  "pfoa_untargeted_plasma",
  "pfna_untargeted_plasma",
  "pfda_untargeted_plasma",
  "pf_hp_a_untargeted_plasma",
  "pf_ud_a_untargeted_plasma"
)

covariates <- c("age_baseline", "sex", "race_binary", "parents_income_new", "site")

q_cutoff_sig_feat <- 0.05
q_cutoff_sig_feat_pca <- 0.000085
```

## Data Loading

```{r load data}
load(
  fs::path(
    dir_data,
    "tl_long_met_untargeted_pfas_workdata.RData"
  )
)

platforms <- names(met_fts_final)
```

```{r load data}
load(
  fs::path(
    dir_results |> dirname(), 
    "1_code",
    "2_longitudinal_metabolomics",
    "temp_data",
    "model_statistics_untargeted_PFAS_longitudinal_metabo.RData")
)

platforms <- names(lmm_random_intercept_knot1_covars_PFAS_output)
```

```{r}
sig_feature_list <- readRDS(
  file = fs::path(
    dir_results |> dirname(),
    "1_code",
    "2_longitudinal_metabolomics",
    "temp_data",
    "sig_JT_feature_by_chemical_pca_corrected.rds"
  )
)
```

```{r load annotatioin data}
feat_annot_l <- readRDS(
  fs::path(
    dir_home,
    "4_Projects",
    "TL_POPs AT_plasma metabolome_complete (ZLi)",
    "0_data",
    "confirmed_unique_annotation.rds"))
```

```{r}
color_code <- data.frame(
  metabolite_name = c("Phytic acid", "Aminoisobutanoate", "Hydroxymyristic acid", "Creatinine", "Quinolinic acid", "Undecylenic acid"),
  class = c("Others", "Amino acid metabolism", "Lipid metabolism", "Amino acid metabolism", "Amino acid metabolism", "Lipid metabolism"),
  color_code = c("grey40", "#1f77b4", "#FFD700", "#1f77b4", "#1f77b4", "#FFD700")
)
```

## Summary

### Annotation of Sig. features

```{r}
sig_feature_annot <- modify2(
  sig_feature_list,
  feat_annot_l,
  ~ lapply(.x, function(z) get_annotation(z, .y))
)
sig_feature_annot <- lapply(sig_feature_annot, function(sub) {
  sub[lengths(sub) > 0]
})
sig_feature_annot <- sig_feature_annot[lengths(sig_feature_annot) > 0]
```

After manually removing the external exposures from metabolites, we would keep results from HILIC columns and C18 +.

```{r}
sig_feature_annot_final <- sig_feature_annot[c("c18pos","hilicneg", "hilicpos")]
```

### Model statistics of sig. features

```{r}
model_summary <- {}
for(i in names(sig_feature_annot_final))
{
  model_df <- met_fts_final[[i]] %>% 
    dplyr::select(-key, -visit)
  covariates_df <- tl_final[,covariates]
  key <- tl_final$key
  visit <- tl_final$visit_year
  
  model_output_by_chemical <- {}  
  for(k in names(sig_feature_annot_final[[i]]))
  {
    met_vec <- sig_feature_annot_final[[i]][[k]]
    x <- tl_final[,k]
    y_vec <- model_df[, met_vec, drop = FALSE]
    model_output <- lapply(
      names(y_vec),
      function(fname){
        y <- y_vec[[fname]]
        fit_lmm_random_intercept_covars_JT_CI(
          x = x, y = y, key = key, visit = visit, covariates_df = covariates_df
          ) %>%
          dplyr::mutate(
            metabolite_name = names(met_vec)[met_vec == fname]
          )
        }
      ) %>% bind_rows()
    model_output_by_chemical[[k]] <- model_output
    
    rm(x, y_vec, model_output)
  }
  model_summary[[i]] <- bind_rows(model_output_by_chemical)
  
  rm(model_df, model_output_by_chemical)
}

model_summary <- modify2(
  model_summary,
  names(model_summary),
  ~ .x %>% 
    dplyr::mutate(
      mode = .y
    )
) %>% bind_rows
```

```{r}
# remove arachidate because it has opposite results across different modes

model_summary <- model_summary %>% 
  dplyr::filter(metabolite_name != "Arachidate")
```

## Forest Plot

```{r}
model_summary <- model_summary %>% 
  dplyr::mutate(
    show_name = case_when(
      metabolite_name == "[C26.0]-Hexacosanoic acid"~ "Hexacosanoic acid",
      .default = metabolite_name
    ),
    pfas_binary = case_when(
      exposure %in% c("pfos_untargeted_plasma", "pf_hx_s_untargeted_plasma", "pf_hp_s_untargeted_plasma") ~ "Sulfonia acids",
      .default = "Carboxylic acids"
    )
  )
model_summary$pfas_name <- chemical_names[match(model_summary$exposure, chemical_variables)]

panel_a <- ggplot(
  model_summary %>% 
    dplyr::filter(beta_type == "main_effect"),
  aes(x = show_name, y = coef)
) +
  geom_point(shape = 20, size = 2, color = "black") +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), width = 0.2, alpha= 0.7, linewidth = 0.7) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ylab("Main effect\ncoefficients") +
  xlab(NULL) +
  facet_grid(
    pfas_name + mode ~ .,
    scales = "free_y", space = "free",
    labeller = labeller(
      mode = c(
        "c18pos" = "C18 (+)",
        "hilicpos" = "HILIC (+)")
    )) +
  coord_flip() +
  theme_classic() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        text = element_text(family="sans"),
        axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 11, color = "black"),
        axis.line.x = element_line(arrow = arrow(length = unit(0.25,"cm"))),
        legend.position = "none",
        panel.background = element_rect(fill="grey95"),
        strip.background = element_rect(fill = "white", color = NA),
        # strip.text = element_text(size = 11, angle = 0),
        strip.text = element_blank())

panel_b <- ggplot(
  model_summary %>% 
    dplyr::filter(beta_type == "interaction"),
  aes(x = show_name, y = coef)
) +
  geom_point(shape = 20, size = 2, color = "black") +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), width = 0.2, alpha= 0.7, linewidth = 0.7) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ylab("Interaction\ncoefficients") +
  xlab(NULL) +
  facet_grid(
    pfas_name + mode ~ .,
    scales = "free_y", space = "free",
    labeller = labeller(
      mode = c(
        "c18pos" = "C18 (+)",
        "hilicpos" = "HILIC (+)")
    )) +
  coord_flip() +
  theme_classic() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        text = element_text(family="sans"),
        axis.text = element_text(size = 10, color = "black"),
        axis.title = element_text(size = 11, color = "black"),
        axis.line.x = element_line(arrow = arrow(length = unit(0.25,"cm"))),
        axis.text.y = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill="grey95"),
        strip.background = element_rect(fill = "white", color = NA),
        strip.text = element_text(size = 9, angle = 0, color = "black"))

png(
  fs::path(
    dir_figures,
    "forest_plot_by_untargeted_PFAS.png" 
  ),
  width = 6, height = 3.5, units = "in", res = 300
)
plot_grid(
  panel_a,
  panel_b,
  nrow = 1,
  rel_widths = c(1,0.7)
)
dev.off()
```

```{r}
#| eval: false
#| include: false

write.csv(
  model_summary,
  fs::path(
    dir_results,
    "Figure 1_statistics.csv"
  ),
  row.names = FALSE
)
```

## Forest Plot for Poster

```{r}
model_summary <- model_summary %>% 
  dplyr::mutate(
    show_name = case_when(
      metabolite_name == "[C26.0]-Hexacosanoic acid"~ "Hexacosanoic acid",
      .default = metabolite_name
    ),
    pfas_binary = case_when(
      exposure %in% c("pfos_untargeted_plasma", "pf_hx_s_untargeted_plasma", "pf_hp_s_untargeted_plasma") ~ "Sulfonia acids",
      .default = "Carboxylic acids"
    )
  )
model_summary$pfas_name <- chemical_names[match(model_summary$exposure, chemical_variables)]

panel_a <- ggplot(
  model_summary %>% 
    dplyr::filter(beta_type == "main_effect"),
  aes(x = show_name, y = coef)
) +
  geom_point(shape = 20, size = 4, color = "black") +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), width = 0.4, alpha= 0.7, linewidth = 1.4) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ylab("Main effect\ncoefficients") +
  xlab(NULL) +
  facet_grid(
    pfas_name + mode ~ .,
    scales = "free_y", space = "free",
    labeller = labeller(
      mode = c(
        "c18pos" = "C18 (+)",
        "hilicpos" = "HILIC (+)")
    )) +
  coord_flip() +
  theme_classic() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        text = element_text(family="sans"),
        axis.text = element_text(size = 24, color = "black"),
        axis.title = element_text(size = 28, color = "black"),
        axis.line.x = element_line(arrow = arrow(length = unit(0.25,"cm"))),
        legend.position = "none",
        panel.background = element_rect(fill="grey95"),
        strip.background = element_rect(fill = "white", color = NA),
        # strip.text = element_text(size = 11, angle = 0),
        strip.text = element_blank())

panel_b <- ggplot(
  model_summary %>% 
    dplyr::filter(beta_type == "interaction"),
  aes(x = show_name, y = coef)
) +
  geom_point(shape = 20, size = 4, color = "black") +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), width = 0.4, alpha= 0.7, linewidth = 1.4) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ylab("Interaction\ncoefficients") +
  xlab(NULL) +
  facet_grid(
    pfas_name + mode ~ .,
    scales = "free_y", space = "free",
    labeller = labeller(
      mode = c(
        "c18pos" = "C18 (+)",
        "hilicpos" = "HILIC (+)")
    )) +
  coord_flip() +
  theme_classic() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        text = element_text(family="sans"),
        axis.text = element_text(size = 24, color = "black"),
        axis.title = element_text(size = 28, color = "black"),
        axis.line.x = element_line(arrow = arrow(length = unit(0.25,"cm"))),
        axis.text.y = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill="grey95"),
        strip.background = element_rect(fill = "white", color = NA),
        strip.text = element_text(size = 20, angle = 0, color = "black"))

png(
  fs::path(
    dir_figures,
    "forest_plot_by_untargeted_PFAS_poster.png" 
  ),
  width = 14, height = 5, units = "in", res = 300
)
plot_grid(
  panel_a,
  panel_b,
  nrow = 1,
  rel_widths = c(1,0.7)
)
dev.off()
```
