---
title: "Pathway analysis - Visualization"
author: "Zhenjiang Li"
date: today
toc: true
toc_expand: 2
format: 
  html:
    code-fold: true
    html-math-method: katex
    fontsize: 16pt
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 1.5rem
embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: console
---

## Environment Setup {.hidden}

```{=html}
<style type="text/css">
caption, .table-caption {
  text-align: left;
}
</style>
```

```{r}
#| echo: false

options(scipen=999)

source(fs::path(here::here(),"2_longitudinal_metabolomics","!libraries.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!directories.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!functions.R"))

library(readxl)
library(scales)
library(latex2exp)
library(ggplot2)
library(ggh4x)

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
#| label: shorten-long-path
#| include: false

create_shortcut <- function(path, short_cut, drive)
{
  return(
    sub(gsub("\\)", "\\\\)", gsub("\\(", "\\\\(", short_cut)), paste0(drive, ":"), path))
}

if(nchar(dir_data) > 80)
{
  system("subst x: /D")
  short_cut <- dir_home |> dirname()
  system(paste0("subst x: \"", short_cut, "\""))
  
  dir_objects_names <- ls(pattern = "^dir_")
  
  dir_list <- mget(dir_objects_names)
  
  dir_list_shortened <- lapply(
    dir_list,
    function(y) create_shortcut(y, short_cut, "x")
  )
  list2env(dir_list_shortened, envir = .GlobalEnv)  
}

rm(dir_objects_names, short_cut, dir_list, dir_list_shortened)
```

## Model Parameters

```{r}
chemical_names <- c("PFOS", "PFHxS", "PFHpS", "PFOA", "PFNA", "PFDA", "PFHpA", "PFUnDa")

chemical_variables <- c(
  "pfos_untargeted_plasma",
  "pf_hx_s_untargeted_plasma",
  "pf_hp_s_untargeted_plasma",
  "pfoa_untargeted_plasma",
  "pfna_untargeted_plasma",
  "pfda_untargeted_plasma",
  "pf_hp_a_untargeted_plasma",
  "pf_ud_a_untargeted_plasma"
)

covariates <- c("age_baseline", "sex", "race_binary", "parents_income_new", "site")

q_cutoff_sig_feat <- 0.2
q_cutoff_sig_feat_pca <- 0.000085

platforms <- c("c18neg", "c18pos", "hilicneg", "hilicpos")

mix_names <- c("PFAS burden score", "Sum Sulfonic Acids", "Sum Carboxylic Acids")
```

## Pathway Figure

### Data Loading

```{r load data}
# Define the main folder path
main_folder <- fs::path(
  dir_results |> dirname(),
  "1_code",
  "2_longitudinal_metabolomics",
  "temp_data",
  "Mummichog"
)

# Get a list of all subfolders (directly inside "Mummichog")
subfolders <- list.dirs(main_folder, recursive = FALSE, full.names = TRUE)
subfolders <- grep(paste(mix_names, collapse = "|"), subfolders, value = T, invert = T)

# Function to find and read the target Excel file inside each subfolder
read_target_excel <- function(subfolder) {
  # Construct full path to the "tables" folder
  tables_folder <- list.dirs(subfolder, recursive = TRUE, full.names = TRUE)
  
  # Identify the correct "tables" folder path
  tables_path <- tables_folder[grepl("tables$", tables_folder)]
  
  # Construct file path to Excel file inside the "tables" folder
  file_path <- file.path(tables_path, "mcg_pathwayanalysis_.xlsx")
  
  # Read Excel file if it exists
  if (file.exists(file_path)) {
    return(read_xlsx(file_path))
  } else {
    return(NULL)  # Return NULL if the file is missing
  }
}

# Read all Excel files into a named list, using subfolder names
excel_list <- lapply(
  subfolders,
  read_target_excel
)

# Assign subfolder names (last part of path) as list names
names(excel_list) <- basename(subfolders)
```

### Summary

```{r}
pathway_summary <- modify(
  excel_list,
  ~ .x %>% 
    dplyr::filter(`p-value` < 0.05 & overlap_size >= 2)
)

# Remove dataframes with zero rows
pathway_summary <- Filter(function(df) nrow(df) > 0, pathway_summary)

# bind all pathways together and add columns for exposure and modes
pathway_summary <- modify2(
  pathway_summary,
  names(pathway_summary),
  ~ .x %>% 
    dplyr::mutate(expo_mode = .y)
) |>
  bind_rows()

pathway_summary$exposure <- sub('.*_', '', pathway_summary$expo_mode)
pathway_summary$mode <- sub('_.*', '', pathway_summary$expo_mode)

pathway_summary$enrichment <- with(
  pathway_summary,
  as.numeric(overlap_size/pathway_size)
)
```

### Dot plot

```{r}
pathway_summary$expo_path <- with(
  pathway_summary,
  interaction(
    exposure, pathway,
    lex.order = T
  )
)
pathway_summary <- pathway_summary %>% 
  dplyr::mutate(
    pfas_binary = case_when(
      exposure %in% c("PFOS", "PFHxS", "PFHpS") ~ "Sulfonic\nacids",
      .default = "Carboxylic\nacids"
    )
  )
pathway_summary <- pathway_summary %>% 
  dplyr::mutate(
    superclass = case_when(
      pathway %in% c("Glycosphingolipid metabolism",
                     "Butanoate metabolism") ~ "Others",
      pathway %in% c("Arachidonic acid metabolism",
                     "Prostaglandin formation from arachidonate",
                     "Bile acid biosynthesis",
                     "Ascorbate (Vitamin C) and Aldarate Metabolism",
                     "C21-steroid hormone biosynthesis and metabolism") ~ 
        "Lipid metabolism",
      pathway %in% c("Histidine metabolism",
                     "Aspartate and asparagine metabolism") ~ 
        "Amino acid metabolism"
    )
  )

ggplot(
  data = pathway_summary,
  aes(x = -log10(`p-value`), y = pathway, size = enrichment, shape = mode)) +
 geom_point(aes(fill = mode, color = mode), show.legend = T) +
 scale_size_continuous(
   range = c(5, 10), 
   name = "Enrichment",
   labels = scales::percent_format(accuracy = 1)) +
 # scale_fill_manual(values = CPCOLS, name = "Mode") +
 # scale_color_manual(values = CPCOLS, name = "Mode") +
 scale_shape_manual(
   values = c(21, 22, 23, 24), name = "Mode",
   labels = c(
     "c18pos" = "C18 (+)",
     "hilicneg" = "HILIC (-)",
     "hilicpos" = "HILIC (+)"
   )) +
  facet_nested(
    exposure + superclass ~ ., 
    scales = "free_y", space = "free",
    strip = strip_split(c("left", "right"))
  ) +
 theme_classic() +
 xlab(expression(-log[10](`p-value`))) +
 ylab(NULL) +
 geom_vline(xintercept = -log10(0.05), linetype = "dashed", color = "red") +
 theme(
   axis.text = element_text(size = 11, color = "black"),
   axis.title = element_text(size = 11, color = "black"),
   axis.ticks = element_blank(),
   axis.line.x = element_line(arrow = arrow(length = unit(0.25,"cm"))),
   legend.title = element_text(face = "plain"),
   legend.position = "bottom",
   legend.box = "horizontal",  # Keep legends in single row
   legend.justification = "left",  # Align legends to left
   legend.box.just = "left",  # Justify legend box to left
   legend.spacing.x = unit(10, "cm"), # Add horizontal space between legends
   legend.margin = margin(l = -9, unit = "cm"),
   panel.grid.major = element_blank(),
   panel.grid.minor = element_blank(),
   panel.background = element_rect(fill="grey95"),
   strip.background = element_rect(fill = "white", color = NA),
   strip.text.y.right = element_text(size = 9, angle = 0, hjust = 0),
   strip.text.y.left = element_text(size = 11)) + # Adjust legend box position
 guides(shape = guide_legend(override.aes = list(size = 10)),
        fill = "none",
        color = "none")

ggsave(
  filename = fs::path(
    dir_figures,
    "pathway_analysis_by_untargeted_PFAS.png"
  ),
  width = 8, height = 5, units = "in", dpi = 600
)
```

```{r}
#| include: false

write.csv(
  pathway_summary,
  file = fs::path(
    dir_results,
    "Figure 2_statistics.csv"
  ),
  row.names = F
)
```

```{r for poster}
pathway_summary$expo_path <- with(
  pathway_summary,
  interaction(
    exposure, pathway,
    lex.order = T
  )
)
pathway_summary <- pathway_summary %>% 
  dplyr::mutate(
    pfas_binary = case_when(
      exposure %in% c("PFOS", "PFHxS", "PFHpS") ~ "Sulfonic\nacids",
      .default = "Carboxylic\nacids"
    )
  )
pathway_summary <- pathway_summary %>% 
  dplyr::mutate(
    superclass = case_when(
      pathway %in% c("Glycosphingolipid metabolism",
                     "Butanoate metabolism") ~ "Others",
      pathway %in% c("Arachidonic acid metabolism",
                     "Prostaglandin formation from arachidonate",
                     "Bile acid biosynthesis",
                     "Ascorbate (Vitamin C) and Aldarate Metabolism",
                     "C21-steroid hormone biosynthesis and metabolism") ~ 
        "Lipid metabolism",
      pathway %in% c("Histidine metabolism",
                     "Aspartate and asparagine metabolism") ~ 
        "Amino acid metabolism"
    )
  )

ggplot(
  data = pathway_summary,
  aes(x = -log10(`p-value`), y = pathway, size = enrichment, shape = mode)) +
 geom_point(aes(fill = mode, color = mode), show.legend = T) +
 scale_size_continuous(
   range = c(5, 10), 
   name = "Enrichment",
   labels = scales::percent_format(accuracy = 1)) +
 # scale_fill_manual(values = CPCOLS, name = "Mode") +
 # scale_color_manual(values = CPCOLS, name = "Mode") +
 scale_shape_manual(
   values = c(21, 22, 23, 24), name = "Mode",
   labels = c(
     "c18pos" = "C18 (+)",
     "hilicneg" = "HILIC (-)",
     "hilicpos" = "HILIC (+)"
   )) +
  facet_nested(
    exposure + superclass ~ ., 
    scales = "free_y", space = "free",
    strip = strip_split(c("left", "right"))
  ) +
 theme_classic() +
 xlab(expression(-log[10](`p-value`))) +
 ylab(NULL) +
 geom_vline(xintercept = -log10(0.05), linetype = "dashed", color = "red") +
 theme(
   axis.text = element_text(size = 24, color = "black"),
   axis.title = element_text(size = 24, color = "black"),
   axis.ticks = element_blank(),
   axis.line.x = element_line(arrow = arrow(length = unit(0.25,"cm"))),
   legend.title = element_text(face = "plain", size = 20),
   legend.text = element_text(size = 20),
   legend.position = "bottom",
   legend.box = "horizontal",  # Keep legends in single row
   legend.justification = "left",  # Align legends to left
   legend.box.just = "left",  # Justify legend box to left
   legend.spacing.x = unit(15, "cm"), # Add horizontal space between legends
   legend.margin = margin(l = -14, unit = "cm"),
   panel.grid.major = element_blank(),
   panel.grid.minor = element_blank(),
   panel.background = element_rect(fill="grey95"),
   strip.background = element_rect(fill = "white", color = NA),
   strip.text.y.right = element_text(size = 20, angle = 0, hjust = 0),
   strip.text.y.left = element_text(size = 24)) + # Adjust legend box position
 guides(shape = guide_legend(override.aes = list(size = 8)),
        fill = "none",
        color = "none")

ggsave(
  filename = fs::path(
    dir_figures,
    "pathway_analysis_by_untargeted_PFAS_poster.png"
  ),
  width = 14, height = 7, units = "in", dpi = 600
)
```

```{r evaluate overlapping pathways}
# Step 1: Count occurrences of each pathway
pathway_counts <- table(pathway_summary$pathway)

# Step 2: Identify pathways appearing in at least two dataframes
common_pathways <- names(pathway_counts[pathway_counts >= 2])

# Step 3: Filter each dataframe to keep only common pathways
pathway_summary_common <- pathway_summary %>% 
  dplyr::filter(pathway %in% common_pathways)

with(
  pathway_summary_common,
  table(pathway, mode))

with(
  pathway_summary_common,
  table(pathway, exposure))
```

There are three PFAS chemicals associated with a single pathway multiple times across modes. Thus, I decided to keep the one with highest enrichment.

```{r}
pathway_summary_final <- pathway_summary %>%
  dplyr::mutate(
    enrichment = overlap_size/pathway_size
  ) %>% 
  dplyr::group_by(exposure, pathway) %>% 
  slice_max(order_by = enrichment, n = 1) %>% 
  ungroup()
```

```{r}
#| include: false

write.csv(
  pathway_summary_final,
  file = fs::path(
    dir_results |> dirname(),
    "1_code",
    "2_longitudinal_metabolomics",
    "temp_data",
    "pathway_figrue_input.csv"
  ),
  row.names = F
)

# mannually added superclass of pathways
```

### Column plot

```{r}
pathway_summary_final <- read.csv(
  file = fs::path(
    dir_results |> dirname(),
    "1_code",
    "2_longitudinal_metabolomics",
    "temp_data",
    "pathway_figrue_input.csv"
  )  
)
```

```{r}
# Create expo_path
pathway_summary_final$expo_path <- with(
  pathway_summary_final,
  interaction(
    exposure, pathway,
    lex.order = T
  )
)
pathway_summary_final <- pathway_summary_final %>% 
  dplyr::mutate(
    pfas_binary = case_when(
      exposure %in% c("PFOS", "PFHxS", "PFHpS") ~ "Sulfonic acids",
      .default = "Carboxylic acids"
    )
  )

ggplot(
  pathway_summary_final,
  aes(x = -log(p.value), y = expo_path, fill = enrichment*100)
) +
  geom_col() +
  geom_text(
    aes(label = exposure, colour = factor(pfas_binary)),
    x = 0, hjust = 0, size = 3
  ) +
  geom_vline(xintercept = -log(0.05), linetype="dashed", color = "red") +
  facet_nested(
    superclass + pathway ~ ., 
    scales = "free_y", space = "free",
    strip = strip_split(c("right", "left"))
  ) +
  ylab(NULL) +
  xlab(expression(-log(italic("p")))) +
  scale_fill_gradient(
    low = "#60A6D1", high = "#08306B",
    name = "Enrichment (%)",
    labels = label_percent(scale = 1)) +
  scale_color_manual(
    labels = c(NULL, NULL),
    values = c("#F4A582", "#A8D08D"),
    name = "PFAS type",
    guide = guide_legend(override.aes = list(
      size = 3.6,
      label = c("Carboxylic acids", "Sulfonic acids")
    ))
  ) +
  theme(legend.position = "bottom",
        legend.box.just = "left",
        legend.text = element_text(size=10),
        legend.title = element_text(size=10, hjust = 0),
        text = element_text(size = 11, color = "black"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.x = element_line(
          arrow = arrow(angle = 30, type = "open", length = unit(0.1, "inches"))),
        axis.line.y = element_line(color = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="grey95"),
        strip.background = element_rect(fill = "white", color = NA),
        strip.text.y.left = element_text(size = 10, angle = 0, hjust = 0),
        strip.text.y.right = element_text(size = 11, angle = 0, hjust = 0))

ggsave(
  filename = fs::path(
    dir_figures,
    "pathway_analysis_by_PFAS.png"
  ),
  width = 8, height = 8, units = "in", dpi = 600
)
```
