---
title: "MWAS analysis and pathway analysis for mixtures"
author: "Zhenjiang Li"
date: today
toc: true
toc_expand: 2
format: 
  html:
    code-fold: true
    html-math-method: katex
    fontsize: 16pt
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 1.5rem
embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: console
---

## Environment Setup {.hidden}

```{=html}
<style type="text/css">
caption, .table-caption {
  text-align: left;
}
</style>
```
```{r}
#| echo: false

options(scipen=999)

source(fs::path(here::here(),"2_longitudinal_metabolomics","!libraries.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!directories.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!functions.R"))

library(nlme)
library(doParallel)
library(foreach)
library(kableExtra)

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
#| label: shorten-long-path
#| include: false

create_shortcut <- function(path, short_cut, drive)
{
  return(
    sub(gsub("\\)", "\\\\)", gsub("\\(", "\\\\(", short_cut)), paste0(drive, ":"), path))
}

if(nchar(dir_data) > 80)
{
  system("subst x: /D")
  short_cut <- dir_home |> dirname()
  system(paste0("subst x: \"", short_cut, "\""))
  
  dir_objects_names <- ls(pattern = "^dir_")
  
  dir_list <- mget(dir_objects_names)
  
  dir_list_shortened <- lapply(
    dir_list,
    function(y) create_shortcut(y, short_cut, "x")
  )
  list2env(dir_list_shortened, envir = .GlobalEnv)  
}

rm(dir_objects_names, short_cut, dir_list, dir_list_shortened)
```

## Model Parameters

```{r}
mix_names <- c("Sum Sulfonic Acids", "Sum Carboxylic Acids")

mix_variables <- c(
  "pfas_sulfonic_acids",
  "pfas_carboxylic_acids"
)

covariates <- c("age_baseline", "sex", "race_binary", "parents_income_new", "site")

q_cutoff_sig_feat_pca <- 0.000085

platforms <- c("c18neg", "c18pos", "hilicneg", "hilicpos")
```

## Data Loading

```{r load data}
load(
  fs::path(
    dir_data,
    "tl_long_met_untargeted_pfas_workdata.RData"
  )
)

platforms <- names(met_fts_final)
```

## LMM-based MWAS

```{r}
#| eval: false

start_time <- Sys.time()

lmm_random_intercept_covars_PFAS_mix_output <- {}
for(i in 1:length(platforms))
{
  print(i)
  model_df <- met_fts_final[[i]] %>% 
    dplyr::select(-key, -visit)
  covariates_df <- tl_final[,covariates]
  key <- tl_final$key
  visit <- tl_final$visit_year
    
  output_by_mix <- {}
  for(k in 1:length(mix_variables))
  {
    print(mix_variables[k])
    x <- tl_final[,mix_variables[k]]
    cl <- makeCluster(detectCores()-2)
    registerDoParallel(cl)
    model_output <- foreach(j = 1:dim(model_df)[2], .combine = rbind, .packages = c("nlme")) %dopar%
      fit_lmm_random_intercept_covars_JT(x = x, y = model_df[,j], key = key, visit = visit, covariates_df)
    stopCluster(cl)
    
    model_output <- model_output %>%
      as.data.frame %>%
      mutate_at(vars(coef, se, statistic, pvalue, pvalue_interaction, L_ratio), as.numeric)
    
    model_output$feature <- rep(colnames(model_df), each = 2)
    
    model_output$p_adjust_interaction <- p.adjust(model_output$pvalue_interaction, method = "BH")
    
    output_by_mix[[k]] <- model_output
    
    rm(model_output, x)
  }
  
  lmm_random_intercept_covars_PFAS_mix_output[[i]] <- output_by_mix |>
    bind_rows()
  
  rm(output_by_mix, model_df)
}
names(lmm_random_intercept_covars_PFAS_mix_output) <- platforms

save(lmm_random_intercept_covars_PFAS_mix_output,
     file = fs::path(
       dir_results |> dirname(), 
       "1_code",
       "2_longitudinal_metabolomics",
       "temp_data",
       "model_statistics_untargeted_PFAS_mix_longitudinal_metabo.RData"))

end_time <- Sys.time()
end_time - start_time
```

```{r}
load(
  fs::path(
    dir_results |> dirname(),
    "1_code",
    "2_longitudinal_metabolomics",
    "temp_data",
    "model_statistics_untargeted_PFAS_mix_longitudinal_metabo.RData"
  )
)
```

## Summary

<!-- ### Raw p-values \< 0.05 -->

<!-- ```{r} -->

<!-- sig_list <- lapply( -->

<!--   lmm_random_intercept_covars_PFAS_mix_output, -->

<!--   function(df) get_sig_by_chemical(df, "pvalue", 0.05) -->

<!-- ) |> -->

<!--   modify2( -->

<!--     names(lmm_random_intercept_covars_PFAS_mix_output), -->

<!--     ~ .x %>%  -->

<!--       dplyr::mutate(mode = .y) -->

<!--   ) |> -->

<!--   bind_rows() %>%  -->

<!--   dplyr::mutate( -->

<!--     exposure = factor(exposure, levels = mix_variables) -->

<!--   ) %>%  -->

<!--   dplyr::arrange(mode, exposure) -->

<!-- sig_list$PFAS <- mix_names[match(sig_list$exposure, mix_variables)] -->

<!-- ``` -->

<!-- ```{r} -->

<!-- sig_list %>%  -->

<!--   dplyr::select(mode, PFAS, pvalue) |> -->

<!--   kbl( -->

<!--     col.names = c("Mode", "PFAS mixtures", "# of Sig (p < 0.05)") -->

<!--   ) |> -->

<!--   kable_paper("hover") -->

<!-- ``` -->

<!-- ### Adjusted p-values \< 0.05 -->

<!-- ```{r} -->

<!-- sig_list <- lapply( -->

<!--   lmm_random_intercept_covars_PFAS_mix_output, -->

<!--   function(df) get_sig_by_chemical(df, "p_adjust", 0.05) -->

<!-- ) |> -->

<!--   modify2( -->

<!--     names(lmm_random_intercept_covars_PFAS_mix_output), -->

<!--     ~ .x %>%  -->

<!--       dplyr::mutate(mode = .y) -->

<!--   ) |> -->

<!--   bind_rows() %>%  -->

<!--   dplyr::mutate( -->

<!--     exposure = factor(exposure, levels = mix_variables) -->

<!--   ) %>%  -->

<!--   dplyr::arrange(mode, exposure) -->

<!-- sig_list$PFAS <- mix_names[match(sig_list$exposure, mix_variables)] -->

<!-- ``` -->

<!-- ```{r} -->

<!-- sig_list %>%  -->

<!--   dplyr::select(mode, PFAS, p_adjust) |> -->

<!--   kbl( -->

<!--     col.names = c("Mode", "PFAS mixtures", "# of Sig (adjusted p < 0.05)") -->

<!--   ) |> -->

<!--   kable_paper("hover") -->

<!-- ``` -->

### PCA-corrected p-values

```{r get mode-wide adjusted p-values}
#| eval: false

p_threshold_pca <- modify(
  met_fts_final,
  ~ {
    pca_mwas <- prcomp(.x[,-c(1:2)])
    eigenvalues_mwas <- pca_mwas$sdev^2
    M_eff_mwas <- sum(eigenvalues_mwas > 1)
    0.05/M_eff_mwas
  }
)

# return adjusted p threshold 0.000078
```

```{r}
sig_list <- lapply(
  lmm_random_intercept_covars_PFAS_mix_output,
  function(df) get_sig_JT_by_chemical(df, "pvalue_interaction", q_cutoff_sig_feat_pca)
) |>
  modify2(
    names(lmm_random_intercept_covars_PFAS_mix_output),
    ~ .x %>% 
      dplyr::mutate(mode = .y)
  ) |>
  bind_rows() %>% 
  dplyr::mutate(
    exposure = factor(exposure, levels = mix_variables)
  ) %>% 
  dplyr::arrange(mode, exposure)

sig_list$PFAS <- mix_names[match(sig_list$exposure, mix_variables)]
```

```{r}
sig_list %>% 
  dplyr::select(mode, PFAS, pvalue_interaction) |>
  kbl(
    col.names = c("Mode", "PFAS mixtures", "# of Sig (adjusted p < 0.000085)")
  ) |>
  kable_paper("hover")
```

```{r}
sig_list %>% 
  dplyr::select(mode, PFAS, pvalue_interaction) %>% 
  dplyr::group_by(PFAS) %>% 
  dplyr::reframe(sum = sum(pvalue_interaction, na.rm = T))
```

## Manuscript

I will try pca-adjusted p values first.

```{r extract significant features}
sig_feature_list <- lapply(
  lmm_random_intercept_covars_PFAS_mix_output,
  function(df) get_sig_JT_features_by_chemical(df, "pvalue_interaction", q_cutoff_sig_feat_pca)
)

saveRDS(
  sig_feature_list,
  file = fs::path(
    dir_results |> dirname(),
    "1_code",
    "2_longitudinal_metabolomics",
    "temp_data",
    "sig_JT_feature_by_mix_pca_corrected.rds"
  )
)
```

## Pathway Analysis

```{r}
for(i in 1:length(platforms))
{
  for(j in 1:length(mix_variables))
  {
    mum_wkpath <- fs::path(
      dir_results |> dirname(),
      "1_code",
      "2_longitudinal_metabolomics",
      "temp_data",
      "Mummichog",
      paste0(platforms[i], "_", mix_names[j])
    )
    
    if(file.exists(mum_wkpath)){
      do.call(function(x) unlink(x, recursive = T), list(list.files(mum_wkpath, full.names = T)))
    }else{
      dir.create(mum_wkpath)
    }
    
    mum_input <- lmm_random_intercept_covars_PFAS_mix_output[[i]] %>% 
      dplyr::filter(exposure == mix_variables[j]) %>% 
      dplyr::group_by(feature) %>% 
      dplyr::slice(1) %>% 
      dplyr::ungroup() %>% 
      dplyr::select(feature, pvalue_interaction, L_ratio)
    mum_input$mz <- as.numeric(sub('_.*', '', mum_input$feature))
    mum_input$rt <- as.numeric(sub('.*_', '', mum_input$feature))
    mum_input <- mum_input %>%
      dplyr::select(mz, rt, pvalue_interaction, L_ratio)
    colnames(mum_input) <- c("mz", "rtime", "p-value", "t-score")
    
    write.table(
      mum_input,
      fs::path(
        mum_wkpath,
        paste0("sum_table_", mix_variables[j], "_", platforms[i], ".txt")
      ),
      quote = F, row.names = F, sep = "\t"
    ) 
  }
}
```

```{r}
start_time <- Sys.time()

for(i in 1:length(platforms))
{
  for(j in 1:length(mix_variables))
  {
    mum_wkpath <- fs::path(
      dir_results |> dirname(),
      "1_code",
      "2_longitudinal_metabolomics",
      "temp_data",
      "Mummichog",
      paste0(platforms[i], "_", mix_names[j])
    )
    
    feat_table_name <- platforms[i]
    if(grepl("neg", feat_table_name))
    {
      mode <- "negative"
    }else{
      mode <- "positive"
    }
    
    cmd_code <- paste("python -m mummichog.main -f",
                      paste0("sum_table_", mix_variables[j], "_", platforms[i], ".txt"),
                      "-p 500 -c ", q_cutoff_sig_feat_pca, " -m ", mode, " -z TRUE")
    print(cmd_code)
    setwd(mum_wkpath)
    system(cmd_code)
  }
}

end_time <- Sys.time()
end_time - start_time
```
