---
title: "Manuscript Preparation"
author: "Zhenjiang Li"
date: today
toc: true
toc_expand: 2
format: 
  html:
    code-fold: true
    html-math-method: katex
    fontsize: 16pt
    grid:
      sidebar-width: 0px
      body-width: 1500px
      margin-width: 500px
      gutter-width: 1.5rem
embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: console
---

## Environment Setup {.hidden}

```{=html}
<style type="text/css">
caption, .table-caption {
  text-align: left;
}
</style>
```
```{r}
#| echo: false

options(scipen=999)

source(fs::path(here::here(),"2_longitudinal_metabolomics","!libraries.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!directories.R"))
source(fs::path(here::here(),"2_longitudinal_metabolomics","!functions.R"))

library(table1)

options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
#| label: shorten-long-path
#| include: false

create_shortcut <- function(path, short_cut, drive)
{
  return(
    sub(gsub("\\)", "\\\\)", gsub("\\(", "\\\\(", short_cut)), paste0(drive, ":"), path))
}

if(nchar(dir_data) > 80)
{
  system("subst x: /D")
  short_cut <- dir_home |> dirname()
  system(paste0("subst x: \"", short_cut, "\""))
  
  dir_objects_names <- ls(pattern = "^dir_")
  
  dir_list <- mget(dir_objects_names)
  
  dir_list_shortened <- lapply(
    dir_list,
    function(y) create_shortcut(y, short_cut, "x")
  )
  list2env(dir_list_shortened, envir = .GlobalEnv)  
}

rm(dir_objects_names, short_cut, dir_list, dir_list_shortened)
```

## Model Parameters

```{r}
chemical_names <- c("PFOS", "PFHxS", "PFHpS", "PFOA", "PFNA", "PFDA", "PFHpA", "PFUnDa")

chemical_variables <- c(
  "pfos_untargeted_plasma",
  "pf_hx_s_untargeted_plasma",
  "pf_hp_s_untargeted_plasma",
  "pfoa_untargeted_plasma",
  "pfna_untargeted_plasma",
  "pfda_untargeted_plasma",
  "pf_hp_a_untargeted_plasma",
  "pf_ud_a_untargeted_plasma"
)

mix_names <- c("Sum Sulfonic Acids", "Sum Carboxylic Acids")

mix_variables <- c(
  "pfas_sulfonic_acids",
  "pfas_carboxylic_acids"
)

covariates <- c("age_baseline", "sex", "race_binary", "parents_income_new", "site")
```

## Data Loading

```{r load data}
load(
  fs::path(
    dir_data,
    "tl_long_met_untargeted_pfas_workdata.RData"
  )
)

platforms <- names(met_fts_final)
```

## Sample Size

```{r}
length(unique(tl_final$key))

length(unique(met_fts_final[[1]]$key))

model_data <- inner_join(
  tl_final,
  met_fts_final[[1]],
  by = c("key", "visit")
) %>% 
  drop_na(all_of(covariates))
length(unique(model_data$key))

met_fts_final[[1]] |> dim()
```

## Table 1

```{r}
table1(as.formula(paste0(
  "~",
  paste(covariates, collapse = "+"),
  "+",
  paste(chemical_variables, collapse = "+")
)), data = tl_final %>% 
  dplyr::group_by(key) %>% 
  slice(1))
```

```{r}
table1(
  ~ as.character(race),
  data = tl_final %>% 
  dplyr::group_by(key) %>% 
  slice(1)
)
```

## Table 2

```{r}
table1(as.formula(paste0(
  "~",
  paste(c(chemical_variables, mix_variables), collapse = "+"),
  "| visit"
)), data = tl_final
)
```
